//! Cryptographic primitives, matching the Go implementation exactly.
//!
//! Bounce uses four primitives:
//!
//! - **Ed25519** for device identity and every frame signature. The device's
//!   signing key is its Tor hidden service key, so the public key is recoverable
//!   from the device address (see [`crate::onion`]).
//! - **X25519** for the key agreement that lets encrypted devices relay frames
//!   they cannot read.
//! - **AES-256-GCM** for frame and chunk encryption, in Go's
//!   `NewGCMWithRandomNonce` layout: a fresh 12 byte nonce is generated per
//!   sealing operation and prepended to the ciphertext.
//! - **BLAKE3** for the digest that is signed, and for deriving group IDs.
//!
//! ## Tor keys are pre-expanded
//!
//! Tor stores hidden service keys in *expanded* form: 64 bytes holding the
//! clamped scalar followed by the nonce prefix, rather than the 32 byte seed
//! that the key would normally be derived from. Bounce signs with that key
//! directly, so [`SigningKey::from_expanded_bytes`] bypasses the usual
//! seed-to-scalar derivation. Signatures are still ordinary Ed25519 and verify
//! against the public key recovered from the address.

use aes_gcm::aead::{Aead, KeyInit, Payload};
use aes_gcm::{Aes256Gcm, Nonce};
use ed25519_dalek::hazmat::{raw_sign, ExpandedSecretKey};
use ed25519_dalek::{Signature, Signer, SigningKey, Verifier, VerifyingKey};
use rand::RngCore;
use sha2::Sha512;

use crate::error::{Error, Result};
use crate::onion;

pub use ed25519_dalek::{PUBLIC_KEY_LENGTH, SECRET_KEY_LENGTH, SIGNATURE_LENGTH};

/// Size of the nonce AES-GCM uses, and the number of bytes prepended to every
/// ciphertext.
pub const GCM_NONCE_LENGTH: usize = 12;

/// Size of an X25519 public or private key.
pub const X25519_KEY_LENGTH: usize = 32;

// -------------------------------------------------------------------------
// Ed25519
// -------------------------------------------------------------------------

/// A device's Ed25519 signing key.
///
/// Wraps either a seed-derived key or a Tor-style pre-expanded key; both
/// produce identical signatures for a given public key.
#[derive(Clone)]
pub enum DeviceKey {
    /// A key derived from a 32 byte seed, as generated by `ed25519.GenerateKey`
    /// in Go's standard library.
    Seed(Box<SigningKey>),
    /// A Tor hidden service key: the clamped scalar and nonce prefix, already
    /// expanded.
    ///
    /// The raw 64 bytes are kept rather than a parsed `ExpandedSecretKey`,
    /// which is deliberately not `Clone` — it is re-parsed for each signature.
    Expanded {
        bytes: Box<[u8; 64]>,
        public: VerifyingKey,
    },
}

impl DeviceKey {
    /// Generate a fresh device key.
    pub fn generate() -> Self {
        DeviceKey::Seed(Box::new(SigningKey::generate(&mut rand::rngs::OsRng)))
    }

    /// Load a key from a 32 byte seed.
    pub fn from_seed(seed: &[u8; SECRET_KEY_LENGTH]) -> Self {
        DeviceKey::Seed(Box::new(SigningKey::from_bytes(seed)))
    }

    /// Load a Tor hidden service key: 64 bytes of clamped scalar followed by
    /// nonce prefix, as written to `hs_ed25519_secret_key`.
    pub fn from_expanded_bytes(bytes: &[u8; 64]) -> Result<Self> {
        let public = VerifyingKey::from(&ExpandedSecretKey::from_bytes(bytes));
        Ok(DeviceKey::Expanded {
            bytes: Box::new(*bytes),
            public,
        })
    }

    /// Load a key from either representation, choosing by length.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self> {
        match bytes.len() {
            32 => {
                let mut seed = [0u8; 32];
                seed.copy_from_slice(bytes);
                Ok(Self::from_seed(&seed))
            }
            64 => {
                let mut expanded = [0u8; 64];
                expanded.copy_from_slice(bytes);
                Self::from_expanded_bytes(&expanded)
            }
            other => Err(Error::InvalidKey(format!(
                "ed25519 private key must be 32 or 64 bytes, got {other}"
            ))),
        }
    }

    /// This key's public half.
    pub fn public_key(&self) -> [u8; PUBLIC_KEY_LENGTH] {
        match self {
            DeviceKey::Seed(key) => key.verifying_key().to_bytes(),
            DeviceKey::Expanded { public, .. } => public.to_bytes(),
        }
    }

    /// The onion service address this key produces, which is this device's
    /// identity throughout the protocol.
    pub fn address(&self) -> String {
        onion::address_from_public_key(&self.public_key())
    }

    /// Sign a message.
    pub fn sign(&self, message: &[u8]) -> [u8; SIGNATURE_LENGTH] {
        match self {
            DeviceKey::Seed(key) => key.sign(message).to_bytes(),
            DeviceKey::Expanded { bytes, public } => {
                let secret = ExpandedSecretKey::from_bytes(bytes);
                raw_sign::<Sha512>(&secret, message, public).to_bytes()
            }
        }
    }

    /// Serialize the private key: 32 bytes for a seed key, 64 for an expanded
    /// key.
    pub fn to_private_bytes(&self) -> Vec<u8> {
        match self {
            DeviceKey::Seed(key) => key.to_bytes().to_vec(),
            DeviceKey::Expanded { bytes, .. } => bytes.to_vec(),
        }
    }

    /// The key in Tor's on-disk hidden service format: 32 bytes of clamped
    /// scalar followed by 32 bytes of nonce prefix.
    ///
    /// This is what Tor calls an expanded secret key, and it is the only form
    /// an onion service identity can be supplied in — arti's `HsIdKeypair`
    /// takes nothing else, deliberately, so that custom-generated addresses
    /// remain possible.
    ///
    /// A seed key is expanded the way Ed25519 key generation does it
    /// internally: SHA-512 of the seed, with the standard clamping applied to
    /// the low half. That yields the same public key and the same signatures,
    /// so a device's address is unchanged by going through this.
    pub fn to_expanded_bytes(&self) -> [u8; 64] {
        match self {
            DeviceKey::Expanded { bytes, .. } => **bytes,
            DeviceKey::Seed(key) => {
                use sha2::Digest;

                let digest = Sha512::digest(key.to_bytes());
                let mut expanded = [0u8; 64];
                expanded.copy_from_slice(&digest);

                // Clamp: clear the low three bits, clear the top bit, set the
                // second-highest. Ed25519 requires this of every scalar.
                expanded[0] &= 248;
                expanded[31] &= 63;
                expanded[31] |= 64;

                expanded
            }
        }
    }
}

impl std::fmt::Debug for DeviceKey {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // Never print private key material.
        f.debug_struct("DeviceKey")
            .field("address", &self.address())
            .finish_non_exhaustive()
    }
}

/// Verify a signature against the Ed25519 public key encoded in `address`.
///
/// Returns `false` rather than an error for any failure, matching
/// `TorNetwork.VerifySignature` in the Go implementation: a malformed address
/// and a bad signature are equally "not verified".
pub fn verify_signature(address: &str, message: &[u8], signature: &[u8]) -> bool {
    let Ok(public_bytes) = onion::public_key_from_address(address) else {
        return false;
    };
    let Ok(verifying_key) = VerifyingKey::from_bytes(&public_bytes) else {
        return false;
    };
    let Ok(signature_bytes) = <[u8; SIGNATURE_LENGTH]>::try_from(signature) else {
        return false;
    };
    verifying_key
        .verify(message, &Signature::from_bytes(&signature_bytes))
        .is_ok()
}

// -------------------------------------------------------------------------
// BLAKE3
// -------------------------------------------------------------------------

/// BLAKE3-256 of a payload. This is the digest that gets signed, never the
/// payload itself.
pub fn hash(payload: &[u8]) -> [u8; 32] {
    *blake3::hash(payload).as_bytes()
}

/// The first 16 bytes of the BLAKE3 output stream, used to derive a group's ID
/// from its immutable creation state.
pub fn hash_16(payload: &[u8]) -> [u8; 16] {
    let full = blake3::hash(payload);
    let mut out = [0u8; 16];
    out.copy_from_slice(&full.as_bytes()[..16]);
    out
}

// -------------------------------------------------------------------------
// X25519
// -------------------------------------------------------------------------

/// Generate an X25519 keypair, returned as `(private, public)`.
pub fn generate_x25519_keypair() -> ([u8; X25519_KEY_LENGTH], [u8; X25519_KEY_LENGTH]) {
    let secret = x25519_dalek::StaticSecret::random_from_rng(rand::rngs::OsRng);
    let public = x25519_dalek::PublicKey::from(&secret);
    (secret.to_bytes(), public.to_bytes())
}

/// Derive the public key for an X25519 private key.
pub fn x25519_public_key(private_key: &[u8]) -> Result<[u8; X25519_KEY_LENGTH]> {
    let secret = static_secret(private_key)?;
    Ok(x25519_dalek::PublicKey::from(&secret).to_bytes())
}

/// Perform an X25519 exchange, producing the shared secret Bounce uses as a key
/// encryption key.
pub fn generate_kek(private_key: &[u8], counterparty_public_key: &[u8]) -> Result<[u8; 32]> {
    let secret = static_secret(private_key)?;
    let public_bytes: [u8; X25519_KEY_LENGTH] = counterparty_public_key
        .try_into()
        .map_err(|_| Error::InvalidKey("x25519 public key must be 32 bytes".into()))?;
    let public = x25519_dalek::PublicKey::from(public_bytes);
    Ok(secret.diffie_hellman(&public).to_bytes())
}

fn static_secret(private_key: &[u8]) -> Result<x25519_dalek::StaticSecret> {
    let bytes: [u8; X25519_KEY_LENGTH] = private_key
        .try_into()
        .map_err(|_| Error::InvalidKey("x25519 private key must be 32 bytes".into()))?;
    Ok(x25519_dalek::StaticSecret::from(bytes))
}

// -------------------------------------------------------------------------
// AES-256-GCM
// -------------------------------------------------------------------------

/// Encrypt with AES-256-GCM, prepending a freshly generated nonce.
///
/// The output layout is `nonce || ciphertext || tag`, which is what Go's
/// `cipher.NewGCMWithRandomNonce(...).Seal` produces.
pub fn seal(key: &[u8], plaintext: &[u8]) -> Result<Vec<u8>> {
    let cipher = aes_256_gcm(key)?;

    let mut nonce_bytes = [0u8; GCM_NONCE_LENGTH];
    rand::rngs::OsRng.fill_bytes(&mut nonce_bytes);
    let nonce = Nonce::from_slice(&nonce_bytes);

    let ciphertext = cipher
        .encrypt(
            nonce,
            Payload {
                msg: plaintext,
                aad: &[],
            },
        )
        .map_err(|_| Error::DecryptionFailed)?;

    let mut out = Vec::with_capacity(GCM_NONCE_LENGTH + ciphertext.len());
    out.extend_from_slice(&nonce_bytes);
    out.extend_from_slice(&ciphertext);
    Ok(out)
}

/// Decrypt a buffer produced by [`seal`], reading the nonce off the front.
pub fn open(key: &[u8], sealed: &[u8]) -> Result<Vec<u8>> {
    if sealed.len() < GCM_NONCE_LENGTH {
        return Err(Error::DecryptionFailed);
    }
    let cipher = aes_256_gcm(key)?;
    let (nonce_bytes, ciphertext) = sealed.split_at(GCM_NONCE_LENGTH);
    cipher
        .decrypt(
            Nonce::from_slice(nonce_bytes),
            Payload {
                msg: ciphertext,
                aad: &[],
            },
        )
        .map_err(|_| Error::DecryptionFailed)
}

/// Generate a fresh 256 bit data encryption key.
pub fn generate_dek() -> [u8; 32] {
    let mut dek = [0u8; 32];
    rand::rngs::OsRng.fill_bytes(&mut dek);
    dek
}

fn aes_256_gcm(key: &[u8]) -> Result<Aes256Gcm> {
    if key.len() != 32 {
        return Err(Error::InvalidKey(format!(
            "AES-256 key must be 32 bytes, got {}",
            key.len()
        )));
    }
    Aes256Gcm::new_from_slice(key).map_err(|_| Error::InvalidKey("bad AES key".into()))
}

/// Fill a buffer with cryptographically secure random bytes.
pub fn random_bytes(len: usize) -> Vec<u8> {
    let mut buf = vec![0u8; len];
    rand::rngs::OsRng.fill_bytes(&mut buf);
    buf
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sign_and_verify_via_address() {
        let key = DeviceKey::generate();
        let message = b"a frame digest";
        let signature = key.sign(message);
        assert!(verify_signature(&key.address(), message, &signature));
    }

    #[test]
    fn verification_rejects_tampering() {
        let key = DeviceKey::generate();
        let signature = key.sign(b"original");
        assert!(!verify_signature(&key.address(), b"modified", &signature));

        let other = DeviceKey::generate();
        assert!(!verify_signature(&other.address(), b"original", &signature));

        assert!(!verify_signature("not-an-onion-address", b"original", &signature));
        assert!(!verify_signature(&key.address(), b"original", &[0u8; 10]));
    }

    #[test]
    fn expanded_keys_match_seed_keys() {
        // Expanding a seed key by hand must produce the same public key and the
        // same signatures as the seed key itself. This is the property that lets
        // us sign with Tor's pre-expanded on-disk format.
        use sha2::Digest;

        let seed = [7u8; 32];
        let seed_key = DeviceKey::from_seed(&seed);

        let digest = Sha512::digest(seed);
        let mut expanded = [0u8; 64];
        expanded.copy_from_slice(&digest);

        let expanded_key = DeviceKey::from_expanded_bytes(&expanded).unwrap();

        assert_eq!(seed_key.public_key(), expanded_key.public_key());
        assert_eq!(seed_key.address(), expanded_key.address());

        let message = b"sign me";
        assert_eq!(seed_key.sign(message), expanded_key.sign(message));
        assert!(verify_signature(
            &expanded_key.address(),
            message,
            &expanded_key.sign(message)
        ));
    }

    #[test]
    fn expanding_a_seed_key_preserves_its_identity() {
        // The Tor transport hands `to_expanded_bytes` to arti as the onion
        // service identity. If expansion changed the public key, a device would
        // come up under a different address than the one its contacts know.
        let key = DeviceKey::generate();
        let expanded = DeviceKey::from_expanded_bytes(&key.to_expanded_bytes()).unwrap();

        assert_eq!(expanded.public_key(), key.public_key());
        assert_eq!(expanded.address(), key.address());
        assert_eq!(expanded.sign(b"a frame digest"), key.sign(b"a frame digest"));
    }

    #[test]
    fn an_already_expanded_key_is_returned_verbatim() {
        let seed_key = DeviceKey::generate();
        let bytes = seed_key.to_expanded_bytes();

        let expanded = DeviceKey::from_expanded_bytes(&bytes).unwrap();
        assert_eq!(expanded.to_expanded_bytes(), bytes);
    }

    #[test]
    fn expansion_produces_a_correctly_clamped_scalar() {
        let expanded = DeviceKey::generate().to_expanded_bytes();

        // Ed25519 clamping, which arti's scalar parsing assumes.
        assert_eq!(expanded[0] & 0b0000_0111, 0, "low three bits must be clear");
        assert_eq!(expanded[31] & 0b1000_0000, 0, "top bit must be clear");
        assert_eq!(expanded[31] & 0b0100_0000, 0b0100_0000, "bit 254 must be set");
    }

    #[test]
    fn expanded_key_survives_serialization() {
        let key = DeviceKey::generate();
        let seed_bytes = key.to_private_bytes();
        assert_eq!(seed_bytes.len(), 32);

        let reloaded = DeviceKey::from_bytes(&seed_bytes).unwrap();
        assert_eq!(reloaded.address(), key.address());
        assert_eq!(reloaded.sign(b"x"), key.sign(b"x"));
    }

    #[test]
    fn ecdh_is_symmetric() {
        let (alice_private, alice_public) = generate_x25519_keypair();
        let (bob_private, bob_public) = generate_x25519_keypair();

        let alice_kek = generate_kek(&alice_private, &bob_public).unwrap();
        let bob_kek = generate_kek(&bob_private, &alice_public).unwrap();
        assert_eq!(alice_kek, bob_kek);
    }

    #[test]
    fn ecdh_public_key_derivation_is_consistent() {
        let (private, public) = generate_x25519_keypair();
        assert_eq!(x25519_public_key(&private).unwrap(), public);
    }

    #[test]
    fn seal_open_round_trips() {
        let key = generate_dek();
        let plaintext = b"the contents of a frame";
        let sealed = seal(&key, plaintext).unwrap();

        // Nonce is prepended, so the ciphertext grows by nonce + tag.
        assert_eq!(sealed.len(), GCM_NONCE_LENGTH + plaintext.len() + 16);
        assert_eq!(open(&key, &sealed).unwrap(), plaintext);
    }

    #[test]
    fn seal_uses_a_fresh_nonce_each_time() {
        let key = generate_dek();
        let a = seal(&key, b"same plaintext").unwrap();
        let b = seal(&key, b"same plaintext").unwrap();
        assert_ne!(a, b, "nonce reuse would be catastrophic");
        assert_eq!(open(&key, &a).unwrap(), open(&key, &b).unwrap());
    }

    #[test]
    fn open_rejects_wrong_key_and_corruption() {
        let key = generate_dek();
        let other = generate_dek();
        let sealed = seal(&key, b"secret").unwrap();

        assert!(open(&other, &sealed).is_err());
        assert!(open(&key, &sealed[..GCM_NONCE_LENGTH - 1]).is_err());

        let mut corrupted = sealed.clone();
        let last = corrupted.len() - 1;
        corrupted[last] ^= 0xff;
        assert!(open(&key, &corrupted).is_err());
    }

    #[test]
    fn blake3_matches_known_vector() {
        // BLAKE3 of the empty input, from the reference test vectors.
        assert_eq!(
            hex::encode(hash(b"")),
            "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262"
        );
        // The 16 byte group ID derivation is a prefix of the same stream.
        assert_eq!(hash_16(b"")[..], hash(b"")[..16]);
    }
}
